### ISSUE TITLE
NPAF与 Series Informed Activation Function（VanillaNet）的区别

### ISSUE THREAD

**Issue by wsy-yjys** [AchunLee/CLOLN_TGRS#1]
想请问下论文中的NPAF与 Series Informed Activation Function函数（在VanillaNet: the Power of Minimalism in Deep Learning中提出）的区别是什么？

**Comment by AchunLee** [comment]
你好，两个函数的代码实现方案最终是相同的，但是用法及意义不同，我们强调激活后的补偿效应，单个激活值由可训练的邻域空间决定，有利于空间特征传递，尤其是高光谱图像这种逐像素点分类且存在混合像元现象的应用，邻域激活更有一种类似聚类的补偿效果， 并且你会发现这段代码其实更符合我们解释的意义。其次，我们的NAPF当作专用的空间特征增强，并不是所有的激活函数的替代，我们结构中仅在后两层使用来加强特征传递，在特征提取模块中间未使用，是充分考虑了特征意义，并在文中有所解释，并且前期实验说明了这一点。
VanillaNet中更强调数值上非线性的叠加，他是所有激活函数的平替，并且这个代码实现非线性的叠加其实是一种的折中实现方案。
当然，我们在首页已注明代码参考出处。
谢谢你的问题。

**Comment by wsy-yjys** [comment]
好的，谢谢您的详细的回复。这个工作很赞，但还有两点疑问想请教您，
（1）为什么n=49的Inference Times反而比取25要更低？
（2）为什么NPAF的Inference Times比ReLU要更低？

![image](https://github.com/AchunLee/CLOLN_TGRS/assets/78601159/fe88c01d-8976-4e75-a042-cfea31c83977)

**Comment by AchunLee** [comment]
你好，你的问题很好，是这样的，推理时间跟模型的浮点计算量没有直接的正相关性，反而跟模型及其算子的计算密度以及访存量有很大的关系（可以理解为硬件因素），浮点计算量大并不代表推理时间一定高，因为有可能访存快或者计算密度高，推理很快。例如表中的例子，激活ReLU是低计算密度运算，虽然NPAF以及其参数取大值的之后，引入了浮点计算量，但是也变相提高了计算密度，使得计算流水线到这个算子能够保持较高的推理效率，所以整体推理时间可能不变或者更低（这跟具体的计算设备有关），所以我们文中提到是硬件友好型算子。可以类比100m跨栏，跑到跨栏的地方就是计算效率低的地方，现在虽然需要多跑10米（增加了计算量），但是你需要跨的栏杆低了很多（计算效率高了），你跑下来总体时间可能更低。大概这个意思，我们下一篇工作在这方面进行了详细讨论，谢谢关注及提问。
